/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check audio service health
         * @description Check if the audio service is live
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.AudioHealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/audiobook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audiobook
         * @description Get audiobook for a news_id
         */
        get: {
            parameters: {
                query: {
                    /** @description News ID */
                    news_id?: string;
                    /** @description Story ID */
                    story_id?: string;
                    /** @description story */
                    type: string;
                    /** @description 1 */
                    page: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.AudiobookResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/stt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Speech to text
         * @description Convert speech audio to text
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Speech to text request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.SpeechToTextRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.SpeechToTextResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Translate text
         * @description Translate text from source language to target language
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Translation request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.TranslateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.TranslateResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text to speech
         * @description Convert text to speech audio
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Text to speech request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.TextToSpeechRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.TextToSpeechResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Billing Account
         * @description Check Billing Account
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.BillingAccountResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/cancel-subscription-eop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a Stripe individual subscription at the end of the period
         * @description Cancel a Stripe individual subscription at the end of the period
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Cancel subscription request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.CancelIndividualSubscriptionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.CancelIndividualSubscriptionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Stripe checkout session (individual)
         * @description Creates a checkout session and redirects to Stripe's payment page
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Create checkout session request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.CreateIndividualCheckoutSessionRequest"];
                };
            };
            responses: {
                /** @description Redirect to Stripe Checkout */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.CreateIndividualCheckoutSessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Billing Account Usage
         * @description Get Billing Account Usage, assumes free plan
         */
        get: {
            parameters: {
                query?: {
                    /** @description Plan */
                    plan?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.BillingAccountUsageResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get news content
         * @description Get news content by ID
         */
        get: {
            parameters: {
                query: {
                    /** @description Content ID */
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.GetNewsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get news content
         * @description Get news content by ID
         */
        get: {
            parameters: {
                query: {
                    /** @description Language */
                    language: string;
                    /** @description CEFR */
                    cefr: string;
                    /** @description Subject */
                    subject: string;
                    /** @description Page */
                    page: string;
                    /** @description Page size */
                    pagesize: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.NewsItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Get the user's profile information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.GetProfileResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/upsert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert user profile
         * @description Create or update the user's profile
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Profile information */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.UpsertProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.UpsertProfileResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get today's progress
         * @description Get the user's progress for today
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.TodayProgressResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/increment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Increment questions completed
         * @description Increment the number of questions completed for today
         */
        get: {
            parameters: {
                query: {
                    /** @description Amount to increment by */
                    amount: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.IncrementProgressResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get streak information
         * @description Get the user's current streak and completion status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.StreakResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qna": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get or generate a question
         * @description Get an existing question or generate a new one for the given content
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Question request parameters */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.GetQuestionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.GetQuestionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qna/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate an answer
         * @description Evaluate a user's answer to a question
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Answer evaluation request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["models.EvaluateAnswerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.EvaluateAnswerResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get story page content
         * @description Get story content by ID
         */
        get: {
            parameters: {
                query: {
                    /** @description Content ID */
                    id: string;
                    /** @description Page */
                    page: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.GetStoryPageResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/story/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get story QNA context
         * @description Get story QNA context by ID
         */
        get: {
            parameters: {
                query: {
                    /** @description Content ID */
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.GetStoryQNAContextResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/story/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get story query
         * @description Get story query by ID
         */
        get: {
            parameters: {
                query: {
                    /** @description Language */
                    language: string;
                    /** @description CEFR */
                    cefr: string;
                    /** @description Subject */
                    subject: string;
                    /** @description Page */
                    page: string;
                    /** @description Page Size */
                    pagesize: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.StoryItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get type definitions
         * @description Returns type definitions for API documentation (not a real endpoint)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.TypesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Stripe webhook
         * @description Validates and processes incoming webhook events from Stripe
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.WebhookResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspaces
         * @description Get workspaces
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.GetWorkspacesResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create workspace
         * @description Create workspace
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["workspaces.CreateWorkspaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.CreateWorkspaceResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workspaces
         * @description Get workspaces
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.WorkspacesSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/databases/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create database
         * @description Create database
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    workspace_id: string;
                };
                cookie?: never;
            };
            /** @description Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["workspaces.CreateDatabaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.CreateDatabaseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/databases/{database_id}/content/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create content
         * @description Create content
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    workspace_id: string;
                    /** @description Database ID */
                    database_id: string;
                };
                cookie?: never;
            };
            /** @description Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["workspaces.CreateContentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.CreateContentResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/databases/{database_id}/content/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get incomplete jobs
         * @description Get incomplete jobs
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    workspace_id: string;
                    /** @description Database ID */
                    database_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.GetIncompleteJobsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/databases/{database_id}/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get content body
         * @description Get content body
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    workspace_id: string;
                    /** @description Database ID */
                    database_id: string;
                    /** @description Content ID */
                    content_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.GetContentBodyResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/{workspace_id}/databases/{database_id}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query database
         * @description Query database
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Workspace ID */
                    workspace_id: string;
                    /** @description Database ID */
                    database_id: string;
                };
                cookie?: never;
            };
            /** @description Body */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["workspaces.QueryDatabaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["workspaces.QueryDatabaseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["models.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "models.AudioHealthResponse": {
            /** @example live */
            status: string;
        };
        "models.AudiobookResponse": {
            /** @example 300 */
            expires_in: number;
            /** @example https://bucket.s3.amazonaws.com/path/to/file?signed-params */
            url: string;
        };
        "models.BillingAccountResponse": {
            /** @example false */
            canceled: boolean;
            /** @example 2025-01-01T00:00:00Z */
            expiration: string;
            /** @example PRO */
            plan: string;
        };
        "models.BillingAccountUsageResponse": {
            /** @example 100 */
            max_natural_tts_usage: number;
            /** @example 100 */
            max_premium_audiobooks_usage: number;
            /** @example 100 */
            max_premium_stt_usage: number;
            /** @example 10 */
            natural_tts_usage: number;
            /** @example 10 */
            premium_audiobooks_usage: number;
            /** @example 10 */
            premium_stt_usage: number;
        };
        "models.CancelIndividualSubscriptionRequest": Record<string, never>;
        "models.CancelIndividualSubscriptionResponse": {
            /** @example PREMIUM */
            canceled_plan: string;
            /** @example 2025-03-24T12:00:00Z */
            current_expiration: string;
            /** @example true */
            success: boolean;
        };
        "models.CreateIndividualCheckoutSessionRequest": Record<string, never>;
        "models.CreateIndividualCheckoutSessionResponse": {
            /** @example https://checkout.stripe.com/c/pay/123 */
            redirect_url: string;
        };
        /** @enum {string} */
        "models.ERROR_CODE": "PROFILE_NOT_FOUND" | "NO_TRANSCRIPT" | "AUTH_REQUIRED" | "USAGE_LIMIT_REACHED" | "USAGE_RESTRICTED";
        "models.ErrorResponse": {
            /**
             * @example PROFILE_NOT_FOUND
             * @enum {unknown}
             */
            code?: "PROFILE_NOT_FOUND" | "NO_TRANSCRIPT" | "AUTH_REQUIRED" | "USAGE_LIMIT_REACHED" | "USAGE_RESTRICTED";
            /** @example Something went wrong */
            error: string;
        };
        "models.EvaluateAnswerRequest": {
            /** @example Hello */
            answer: string;
            /** @example B1 */
            cefr: string;
            /** @example Bonjour, comment ça va? */
            content: string;
            /** @example What does 'bonjour' mean? */
            question: string;
        };
        "models.EvaluateAnswerResponse": {
            /** @example PASS */
            evaluation: string;
            /** @example Perfect! */
            explanation: string;
        };
        "models.GetNewsResponse": {
            /** @example B1 */
            cefr_level: string;
            /** @example Le contenu complet de l'article... */
            content: string;
            /** @example News */
            content_type: string;
            /** @example 2024-02-26 */
            date_created: string;
            dictionary: components["schemas"]["storage.Dictionary"];
            /** @example French */
            language: string;
            /** @example Un résumé des nouvelles musicales... */
            preview_text: string;
            sources: components["schemas"]["storage.Source"][];
            /** @example L'actualité musicale en bref */
            title: string;
            /** @example Music */
            topic: string;
        };
        "models.GetProfileResponse": {
            /** @example 3 */
            daily_questions_goal?: number;
            /** @example [
             *       "[\"NBA\"]"
             *     ] */
            interested_topics: string[];
            /** @example French */
            learning_language: string;
            /** @example B1 */
            skill_level: string;
            /** @example connortbot */
            username: string;
        };
        "models.GetQuestionRequest": {
            /** @example B1 */
            cefr_level: string;
            /** @example News */
            content_type: string;
            /** @example 123 */
            id: string;
            /**
             * @example vocab
             * @enum {string}
             */
            question_type: "vocab" | "understanding";
        };
        "models.GetQuestionResponse": {
            /** @example What does 'bonjour' mean? */
            question: string;
        };
        "models.GetStoryPageResponse": {
            /** @example B1 */
            cefr_level: string;
            /** @example Le contenu complet de l'article... */
            content: string;
            /** @example Story */
            content_type: string;
            /** @example 2024-02-26 */
            date_created: string;
            /** @example French */
            language: string;
            /** @example 10 */
            pages: number;
            /** @example Un résumé des nouvelles musicales... */
            preview_text: string;
            /** @example L'actualité musicale en bref */
            title: string;
            /** @example Music */
            topic: string;
        };
        "models.GetStoryQNAContextResponse": {
            /** @example Le contexte de l'histoire... */
            context: string;
        };
        "models.IncrementProgressResponse": {
            /** @example 2025-02-26T00:00:00Z */
            date: string;
            /** @example true */
            goal_met: boolean;
            /** @example 5 */
            questions_completed?: number;
            /** @example 123 */
            user_id: string;
        };
        "models.NewsItem": {
            /** @example NONE */
            audiobook_tier: string;
            /** @example B1 */
            cefr_level: string;
            /** @example 2024-02-26T13:01:13.390612Z */
            created_at: string;
            /** @example 2024-02-26 */
            date_created: string;
            /** @example 123 */
            id: string;
            /** @example French */
            language: string;
            /** @example Un résumé des nouvelles musicales... */
            preview_text: string;
            /** @example L'actualité musicale en bref */
            title: string;
            /** @example Music */
            topic: string;
        };
        "models.SpeechToTextRequest": {
            /** @example base64-encoded-audio-content */
            audio_content: string;
            /** @example en-US */
            language_code: string;
            /** @example false */
            premium?: boolean;
        };
        "models.SpeechToTextResponse": {
            /** @example Hello, how are you? */
            transcript: string;
        };
        "models.StoryItem": {
            /** @example NONE */
            audiobook_tier: string;
            /** @example B1 */
            cefr_level: string;
            /** @example 2024-02-26T13:01:13.390612Z */
            created_at: string;
            /** @example 2024-02-26 */
            date_created: string;
            /** @example 123 */
            id: string;
            /** @example French */
            language: string;
            /** @example Un résumé des nouvelles musicales... */
            preview_text: string;
            /** @example L'actualité musicale en bref */
            title: string;
            /** @example Music */
            topic: string;
        };
        "models.StreakResponse": {
            /** @example true */
            completed_today: boolean;
            /** @example 7 */
            streak?: number;
        };
        "models.TextToSpeechRequest": {
            /** @example en-US */
            language_code: string;
            /** @example false */
            natural?: boolean;
            /** @example Hello, how are you? */
            text: string;
            /** @example en-US-Standard-A */
            voice_name: string;
        };
        "models.TextToSpeechResponse": {
            /** @example base64-encoded-audio-content */
            audio_content: string;
        };
        "models.TodayProgressResponse": {
            /** @example 2025-02-26T00:00:00Z */
            date: string;
            /** @example true */
            goal_met: boolean;
            /** @example 5 */
            questions_completed?: number;
            /** @example 123 */
            user_id: string;
        };
        "models.TranslateRequest": {
            /** @example Hello, how are you? */
            sentence: string;
            /** @example en */
            source: string;
            /** @example fr */
            target: string;
        };
        "models.TranslateResponse": {
            /** @example Bonjour, comment allez-vous? */
            sentence?: string;
        };
        "models.TypesResponse": {
            stored_content?: components["schemas"]["whisker_types.StoredContent"];
        };
        "models.UpsertProfileRequest": {
            /** @example 3 */
            daily_questions_goal?: number;
            /** @example [
             *       "[\"NBA\"]"
             *     ] */
            interested_topics: string[];
            /** @example French */
            learning_language: string;
            /** @example B1 */
            skill_level: string;
            /** @example johndoe */
            username: string;
        };
        "models.UpsertProfileResponse": {
            /** @example 123 */
            id?: number;
            /** @example Profile updated successfully */
            message: string;
        };
        "models.WebhookResponse": {
            received?: boolean;
            type?: string;
        };
        "storage.Dictionary": {
            translations?: {
                sentences?: {
                    [key: string]: string;
                };
                words?: {
                    [key: string]: string;
                };
            };
        };
        "storage.Source": {
            content?: string;
            score?: number;
            title?: string;
            url?: string;
        };
        /** @enum {string} */
        "whisker_types.CEFRLevel": "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
        "whisker_types.ContentJob": {
            cefr_level?: components["schemas"]["whisker_types.CEFRLevel"];
            created_at?: string;
            database_id?: string;
            id?: string;
            language_code?: components["schemas"]["whisker_types.LanguageCode"];
            name?: string;
            status?: components["schemas"]["whisker_types.ContentJobStatus"];
            user_id?: string;
        };
        /** @enum {string} */
        "whisker_types.ContentJobStatus": "creation" | "pending" | "running" | "complete" | "failed" | "cancelled";
        /** @enum {string} */
        "whisker_types.LanguageCode": "en" | "es" | "fr";
        "whisker_types.StoredContent": {
            markdown?: string;
            name?: string;
        };
        "workspaces.Content": {
            /** @example A1 */
            cefr_level: components["schemas"]["whisker_types.CEFRLevel"];
            /** @example 2021-01-01T00:00:00Z */
            created_at: string;
            /** @example xxxx-xxxx-xxxx-xxxx */
            database_id: string;
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
            /** @example en */
            language_code: components["schemas"]["whisker_types.LanguageCode"];
            /** @example My Content */
            name: string;
        };
        "workspaces.CreateContentRequest": {
            cefr_level: components["schemas"]["whisker_types.CEFRLevel"];
            /** @description Content creation parameters */
            language_code: components["schemas"]["whisker_types.LanguageCode"];
            /** @description Eventually need to build a more robust request body for other
             *     kinds of content uploads */
            link: string;
            name: string;
        };
        "workspaces.CreateContentResponse": Record<string, never>;
        "workspaces.CreateDatabaseRequest": {
            /** @example My Database */
            name: string;
            /** @example content */
            type: components["schemas"]["workspaces.DatabaseType"];
        };
        "workspaces.CreateDatabaseResponse": {
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
        };
        "workspaces.CreateWorkspaceRequest": {
            /** @example My Workspace */
            name: string;
        };
        "workspaces.CreateWorkspaceResponse": {
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
        };
        "workspaces.Database": {
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
            /** @example My Database */
            name: string;
            /** @example content */
            type: components["schemas"]["workspaces.DatabaseType"];
            /** @example xxxx-xxxx-xxxx-xxxx */
            workspace_id: string;
        };
        /** @enum {string} */
        "workspaces.DatabaseType": "content";
        "workspaces.GetContentBodyResponse": {
            presigned_url: string;
        };
        "workspaces.GetIncompleteJobsResponse": {
            jobs?: components["schemas"]["whisker_types.ContentJob"][];
        };
        "workspaces.GetWorkspacesResponse": {
            workspaces: components["schemas"]["workspaces.Workspace"][];
        };
        "workspaces.QueryDatabaseRequest": {
            /** @example content */
            type: components["schemas"]["workspaces.DatabaseType"];
        };
        "workspaces.QueryDatabaseResponse": {
            content?: components["schemas"]["workspaces.Content"][];
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
            /** @example My Database */
            name: string;
            /** @example content */
            type: components["schemas"]["workspaces.DatabaseType"];
            /** @example xxxx-xxxx-xxxx-xxxx */
            workspace_id: string;
        };
        "workspaces.Workspace": {
            /** @example xxxx-xxxx-xxxx-xxxx */
            id: string;
            /** @example My Workspace */
            name: string;
        };
        "workspaces.WorkspacesSummary": {
            databases: components["schemas"]["workspaces.Database"][];
            workspaces: components["schemas"]["workspaces.Workspace"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
