// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audio": {
            "get": {
                "description": "Check if the audio service is live",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Check audio service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AudioHealthResponse"
                        }
                    }
                }
            }
        },
        "/audio/audiobook": {
            "get": {
                "description": "Get audiobook for a news_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audio"
                ],
                "summary": "Get audiobook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "News ID",
                        "name": "news_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Story ID",
                        "name": "story_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "story",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.AudiobookResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/billing": {
            "get": {
                "description": "Check Billing Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Check Billing Account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillingAccountResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/billing/cancel-subscription-eop": {
            "post": {
                "description": "Cancel a Stripe individual subscription at the end of the period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Cancel a Stripe individual subscription at the end of the period",
                "parameters": [
                    {
                        "description": "Cancel subscription request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CancelIndividualSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CancelIndividualSubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/billing/create-checkout-session": {
            "post": {
                "description": "Creates a checkout session and redirects to Stripe's payment page",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Create a Stripe checkout session (individual)",
                "parameters": [
                    {
                        "description": "Create checkout session request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateIndividualCheckoutSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Redirect to Stripe Checkout",
                        "schema": {
                            "$ref": "#/definitions/models.CreateIndividualCheckoutSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/billing/usage": {
            "get": {
                "description": "Get Billing Account Usage, assumes free plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "billing"
                ],
                "summary": "Get Billing Account Usage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan",
                        "name": "plan",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BillingAccountUsageResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/language/stt": {
            "post": {
                "description": "Convert speech audio to text",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "Speech to text",
                "parameters": [
                    {
                        "description": "Speech to text request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SpeechToTextRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SpeechToTextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/language/translate": {
            "post": {
                "description": "Translate text from source language to target language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "Translate text",
                "parameters": [
                    {
                        "description": "Translation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TranslateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TranslateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/language/tts": {
            "post": {
                "description": "Convert text to speech audio",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "Text to speech",
                "parameters": [
                    {
                        "description": "Text to speech request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TextToSpeechRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TextToSpeechResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/news": {
            "get": {
                "description": "Get news content by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get news content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetNewsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/news/query": {
            "get": {
                "description": "Get news content by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get news content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CEFR",
                        "name": "cefr",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subject",
                        "name": "subject",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page size",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.NewsItem"
                            }
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "description": "Get the user's profile information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/upsert": {
            "post": {
                "description": "Create or update the user's profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Upsert user profile",
                "parameters": [
                    {
                        "description": "Profile information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpsertProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UpsertProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/progress": {
            "get": {
                "description": "Get the user's progress for today",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Get today's progress",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TodayProgressResponse"
                        }
                    }
                }
            }
        },
        "/progress/increment": {
            "get": {
                "description": "Increment the number of questions completed for today",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Increment questions completed",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Amount to increment by",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IncrementProgressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/progress/streak": {
            "get": {
                "description": "Get the user's current streak and completion status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "progress"
                ],
                "summary": "Get streak information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StreakResponse"
                        }
                    }
                }
            }
        },
        "/qna": {
            "post": {
                "description": "Get an existing question or generate a new one for the given content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qna"
                ],
                "summary": "Get or generate a question",
                "parameters": [
                    {
                        "description": "Question request parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetQuestionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/qna/evaluate": {
            "post": {
                "description": "Evaluate a user's answer to a question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "qna"
                ],
                "summary": "Evaluate an answer",
                "parameters": [
                    {
                        "description": "Answer evaluation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EvaluateAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EvaluateAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/story": {
            "get": {
                "description": "Get story content by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "story"
                ],
                "summary": "Get story page content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetStoryPageResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/story/context": {
            "get": {
                "description": "Get story QNA context by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "story"
                ],
                "summary": "Get story QNA context",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetStoryQNAContextResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/story/query": {
            "get": {
                "description": "Get story query by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "story"
                ],
                "summary": "Get story query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language",
                        "name": "language",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CEFR",
                        "name": "cefr",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Subject",
                        "name": "subject",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page Size",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StoryItem"
                            }
                        }
                    }
                }
            }
        },
        "/types": {
            "get": {
                "description": "Returns type definitions for API documentation (not a real endpoint)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Get type definitions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TypesResponse"
                        }
                    }
                }
            }
        },
        "/webhook": {
            "post": {
                "description": "Validates and processes incoming webhook events from Stripe",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stripe"
                ],
                "summary": "Process Stripe webhook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WebhookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces": {
            "get": {
                "description": "Get workspaces",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.GetWorkspacesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/create": {
            "post": {
                "description": "Create workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Create workspace",
                "parameters": [
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateWorkspaceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateWorkspaceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/deleted": {
            "get": {
                "description": "Get deleted summary of workspaces, databases, and content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get deleted summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.DeletedSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/summary": {
            "get": {
                "description": "Get workspaces",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.WorkspacesSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}": {
            "delete": {
                "description": "Delete workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Delete workspace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "no",
                            "soft_delete",
                            "hard_delete"
                        ],
                        "type": "string",
                        "description": "Delete status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.DeleteWorkspaceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/create": {
            "post": {
                "description": "Create database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Create database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateDatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/{database_id}": {
            "delete": {
                "description": "Delete database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Delete database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "no",
                            "soft_delete",
                            "hard_delete"
                        ],
                        "type": "string",
                        "description": "Delete status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.DeleteDatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/{database_id}/content/create": {
            "post": {
                "description": "Create content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Create content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateContentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/{database_id}/content/jobs": {
            "get": {
                "description": "Get incomplete jobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get incomplete jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.GetIncompleteJobsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/{database_id}/content/{content_id}": {
            "get": {
                "description": "Get content body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Get content body",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "content_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.GetContentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Delete content",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Content ID",
                        "name": "content_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "no",
                            "soft_delete",
                            "hard_delete"
                        ],
                        "type": "string",
                        "description": "Delete status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.DeleteContentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workspaces/{workspace_id}/databases/{database_id}/query": {
            "post": {
                "description": "Query database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workspace"
                ],
                "summary": "Query database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.QueryDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/workspaces.QueryDatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AudioHealthResponse": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "live"
                }
            }
        },
        "models.AudiobookResponse": {
            "type": "object",
            "required": [
                "expires_in",
                "url"
            ],
            "properties": {
                "expires_in": {
                    "type": "integer",
                    "example": 300
                },
                "url": {
                    "type": "string",
                    "example": "https://bucket.s3.amazonaws.com/path/to/file?signed-params"
                }
            }
        },
        "models.BillingAccountResponse": {
            "type": "object",
            "required": [
                "canceled",
                "expiration",
                "plan"
            ],
            "properties": {
                "canceled": {
                    "type": "boolean",
                    "example": false
                },
                "expiration": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "plan": {
                    "type": "string",
                    "example": "PRO"
                }
            }
        },
        "models.BillingAccountUsageResponse": {
            "type": "object",
            "required": [
                "max_natural_tts_usage",
                "max_premium_audiobooks_usage",
                "max_premium_stt_usage",
                "natural_tts_usage",
                "premium_audiobooks_usage",
                "premium_stt_usage"
            ],
            "properties": {
                "max_natural_tts_usage": {
                    "type": "integer",
                    "example": 100
                },
                "max_premium_audiobooks_usage": {
                    "type": "integer",
                    "example": 100
                },
                "max_premium_stt_usage": {
                    "type": "integer",
                    "example": 100
                },
                "natural_tts_usage": {
                    "type": "integer",
                    "example": 10
                },
                "premium_audiobooks_usage": {
                    "type": "integer",
                    "example": 10
                },
                "premium_stt_usage": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.CancelIndividualSubscriptionRequest": {
            "type": "object"
        },
        "models.CancelIndividualSubscriptionResponse": {
            "type": "object",
            "required": [
                "canceled_plan",
                "current_expiration",
                "success"
            ],
            "properties": {
                "canceled_plan": {
                    "type": "string",
                    "example": "PREMIUM"
                },
                "current_expiration": {
                    "type": "string",
                    "example": "2025-03-24T12:00:00Z"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.CreateIndividualCheckoutSessionRequest": {
            "type": "object"
        },
        "models.CreateIndividualCheckoutSessionResponse": {
            "type": "object",
            "required": [
                "redirect_url"
            ],
            "properties": {
                "redirect_url": {
                    "type": "string",
                    "example": "https://checkout.stripe.com/c/pay/123"
                }
            }
        },
        "models.ERROR_CODE": {
            "type": "string",
            "enum": [
                "PROFILE_NOT_FOUND",
                "NO_TRANSCRIPT",
                "AUTH_REQUIRED",
                "USAGE_LIMIT_REACHED",
                "USAGE_RESTRICTED"
            ],
            "x-enum-varnames": [
                "PROFILE_NOT_FOUND",
                "NO_TRANSCRIPT",
                "AUTH_REQUIRED",
                "USAGE_LIMIT_REACHED",
                "USAGE_RESTRICTED"
            ]
        },
        "models.ErrorResponse": {
            "type": "object",
            "required": [
                "error"
            ],
            "properties": {
                "code": {
                    "enum": [
                        "PROFILE_NOT_FOUND",
                        "NO_TRANSCRIPT",
                        "AUTH_REQUIRED",
                        "USAGE_LIMIT_REACHED",
                        "USAGE_RESTRICTED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ERROR_CODE"
                        }
                    ],
                    "example": "PROFILE_NOT_FOUND"
                },
                "error": {
                    "type": "string",
                    "example": "Something went wrong"
                }
            }
        },
        "models.EvaluateAnswerRequest": {
            "type": "object",
            "required": [
                "answer",
                "cefr",
                "content",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Hello"
                },
                "cefr": {
                    "type": "string",
                    "example": "B1"
                },
                "content": {
                    "type": "string",
                    "example": "Bonjour, comment ça va?"
                },
                "question": {
                    "type": "string",
                    "example": "What does 'bonjour' mean?"
                }
            }
        },
        "models.EvaluateAnswerResponse": {
            "type": "object",
            "required": [
                "evaluation",
                "explanation"
            ],
            "properties": {
                "evaluation": {
                    "type": "string",
                    "example": "PASS"
                },
                "explanation": {
                    "type": "string",
                    "example": "Perfect!"
                }
            }
        },
        "models.GetNewsResponse": {
            "type": "object",
            "required": [
                "cefr_level",
                "content",
                "content_type",
                "date_created",
                "dictionary",
                "language",
                "preview_text",
                "sources",
                "title",
                "topic"
            ],
            "properties": {
                "cefr_level": {
                    "type": "string",
                    "example": "B1"
                },
                "content": {
                    "type": "string",
                    "example": "Le contenu complet de l'article..."
                },
                "content_type": {
                    "type": "string",
                    "example": "News"
                },
                "date_created": {
                    "type": "string",
                    "example": "2024-02-26"
                },
                "dictionary": {
                    "$ref": "#/definitions/storage.Dictionary"
                },
                "language": {
                    "type": "string",
                    "example": "French"
                },
                "preview_text": {
                    "type": "string",
                    "example": "Un résumé des nouvelles musicales..."
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.Source"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "L'actualité musicale en bref"
                },
                "topic": {
                    "type": "string",
                    "example": "Music"
                }
            }
        },
        "models.GetProfileResponse": {
            "type": "object",
            "required": [
                "interested_topics",
                "learning_language",
                "skill_level",
                "username"
            ],
            "properties": {
                "daily_questions_goal": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 3
                },
                "interested_topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"NBA\"]"
                    ]
                },
                "learning_language": {
                    "type": "string",
                    "example": "French"
                },
                "skill_level": {
                    "type": "string",
                    "example": "B1"
                },
                "username": {
                    "type": "string",
                    "example": "connortbot"
                }
            }
        },
        "models.GetQuestionRequest": {
            "type": "object",
            "required": [
                "cefr_level",
                "content_type",
                "id",
                "question_type"
            ],
            "properties": {
                "cefr_level": {
                    "type": "string",
                    "example": "B1"
                },
                "content_type": {
                    "type": "string",
                    "example": "News"
                },
                "id": {
                    "type": "string",
                    "example": "123"
                },
                "question_type": {
                    "type": "string",
                    "enum": [
                        "vocab",
                        "understanding"
                    ],
                    "example": "vocab"
                }
            }
        },
        "models.GetQuestionResponse": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "example": "What does 'bonjour' mean?"
                }
            }
        },
        "models.GetStoryPageResponse": {
            "type": "object",
            "required": [
                "cefr_level",
                "content",
                "content_type",
                "date_created",
                "language",
                "pages",
                "preview_text",
                "title",
                "topic"
            ],
            "properties": {
                "cefr_level": {
                    "type": "string",
                    "example": "B1"
                },
                "content": {
                    "type": "string",
                    "example": "Le contenu complet de l'article..."
                },
                "content_type": {
                    "type": "string",
                    "example": "Story"
                },
                "date_created": {
                    "type": "string",
                    "example": "2024-02-26"
                },
                "language": {
                    "type": "string",
                    "example": "French"
                },
                "pages": {
                    "type": "integer",
                    "example": 10
                },
                "preview_text": {
                    "type": "string",
                    "example": "Un résumé des nouvelles musicales..."
                },
                "title": {
                    "type": "string",
                    "example": "L'actualité musicale en bref"
                },
                "topic": {
                    "type": "string",
                    "example": "Music"
                }
            }
        },
        "models.GetStoryQNAContextResponse": {
            "type": "object",
            "required": [
                "context"
            ],
            "properties": {
                "context": {
                    "type": "string",
                    "example": "Le contexte de l'histoire..."
                }
            }
        },
        "models.IncrementProgressResponse": {
            "type": "object",
            "required": [
                "date",
                "goal_met",
                "user_id"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2025-02-26T00:00:00Z"
                },
                "goal_met": {
                    "type": "boolean",
                    "example": true
                },
                "questions_completed": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 5
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "models.NewsItem": {
            "type": "object",
            "required": [
                "audiobook_tier",
                "cefr_level",
                "created_at",
                "date_created",
                "id",
                "language",
                "preview_text",
                "title",
                "topic"
            ],
            "properties": {
                "audiobook_tier": {
                    "type": "string",
                    "example": "NONE"
                },
                "cefr_level": {
                    "type": "string",
                    "example": "B1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-02-26T13:01:13.390612Z"
                },
                "date_created": {
                    "type": "string",
                    "example": "2024-02-26"
                },
                "id": {
                    "type": "string",
                    "example": "123"
                },
                "language": {
                    "type": "string",
                    "example": "French"
                },
                "preview_text": {
                    "type": "string",
                    "example": "Un résumé des nouvelles musicales..."
                },
                "title": {
                    "type": "string",
                    "example": "L'actualité musicale en bref"
                },
                "topic": {
                    "type": "string",
                    "example": "Music"
                }
            }
        },
        "models.SpeechToTextRequest": {
            "type": "object",
            "required": [
                "audio_content",
                "language_code"
            ],
            "properties": {
                "audio_content": {
                    "type": "string",
                    "example": "base64-encoded-audio-content"
                },
                "language_code": {
                    "type": "string",
                    "example": "en-US"
                },
                "premium": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.SpeechToTextResponse": {
            "type": "object",
            "required": [
                "transcript"
            ],
            "properties": {
                "transcript": {
                    "type": "string",
                    "example": "Hello, how are you?"
                }
            }
        },
        "models.StoryItem": {
            "type": "object",
            "required": [
                "audiobook_tier",
                "cefr_level",
                "created_at",
                "date_created",
                "id",
                "language",
                "preview_text",
                "title",
                "topic"
            ],
            "properties": {
                "audiobook_tier": {
                    "type": "string",
                    "example": "NONE"
                },
                "cefr_level": {
                    "type": "string",
                    "example": "B1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-02-26T13:01:13.390612Z"
                },
                "date_created": {
                    "type": "string",
                    "example": "2024-02-26"
                },
                "id": {
                    "type": "string",
                    "example": "123"
                },
                "language": {
                    "type": "string",
                    "example": "French"
                },
                "preview_text": {
                    "type": "string",
                    "example": "Un résumé des nouvelles musicales..."
                },
                "title": {
                    "type": "string",
                    "example": "L'actualité musicale en bref"
                },
                "topic": {
                    "type": "string",
                    "example": "Music"
                }
            }
        },
        "models.StreakResponse": {
            "type": "object",
            "required": [
                "completed_today"
            ],
            "properties": {
                "completed_today": {
                    "type": "boolean",
                    "example": true
                },
                "streak": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 7
                }
            }
        },
        "models.TextToSpeechRequest": {
            "type": "object",
            "required": [
                "language_code",
                "text",
                "voice_name"
            ],
            "properties": {
                "language_code": {
                    "type": "string",
                    "example": "en-US"
                },
                "natural": {
                    "type": "boolean",
                    "example": false
                },
                "text": {
                    "type": "string",
                    "example": "Hello, how are you?"
                },
                "voice_name": {
                    "type": "string",
                    "example": "en-US-Standard-A"
                }
            }
        },
        "models.TextToSpeechResponse": {
            "type": "object",
            "required": [
                "audio_content"
            ],
            "properties": {
                "audio_content": {
                    "type": "string",
                    "example": "base64-encoded-audio-content"
                }
            }
        },
        "models.TodayProgressResponse": {
            "type": "object",
            "required": [
                "date",
                "goal_met",
                "user_id"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2025-02-26T00:00:00Z"
                },
                "goal_met": {
                    "type": "boolean",
                    "example": true
                },
                "questions_completed": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 5
                },
                "user_id": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "models.TranslateRequest": {
            "type": "object",
            "required": [
                "sentence",
                "target"
            ],
            "properties": {
                "sentence": {
                    "type": "string",
                    "example": "Hello, how are you?"
                },
                "target": {
                    "type": "string",
                    "example": "fr"
                }
            }
        },
        "models.TranslateResponse": {
            "type": "object",
            "properties": {
                "detected_source_language": {
                    "type": "string",
                    "example": "fr"
                },
                "sentence": {
                    "type": "string",
                    "example": "Bonjour, comment allez-vous?"
                }
            }
        },
        "models.TypesResponse": {
            "type": "object",
            "properties": {
                "soft_delete_status": {
                    "$ref": "#/definitions/workspaces.SoftDeleteStatus"
                },
                "stored_content": {
                    "$ref": "#/definitions/whisker_types.StoredContent"
                }
            }
        },
        "models.UpsertProfileRequest": {
            "type": "object",
            "required": [
                "interested_topics",
                "learning_language",
                "skill_level",
                "username"
            ],
            "properties": {
                "daily_questions_goal": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 3
                },
                "interested_topics": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"NBA\"]"
                    ]
                },
                "learning_language": {
                    "type": "string",
                    "example": "French"
                },
                "skill_level": {
                    "type": "string",
                    "example": "B1"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                }
            }
        },
        "models.UpsertProfileResponse": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 123
                },
                "message": {
                    "type": "string",
                    "example": "Profile updated successfully"
                }
            }
        },
        "models.WebhookResponse": {
            "type": "object",
            "properties": {
                "received": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "storage.Dictionary": {
            "type": "object",
            "properties": {
                "translations": {
                    "type": "object",
                    "properties": {
                        "sentences": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        },
                        "words": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "storage.Source": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "whisker_types.CEFRLevel": {
            "type": "string",
            "enum": [
                "A1",
                "A2",
                "B1",
                "B2",
                "C1",
                "C2"
            ],
            "x-enum-varnames": [
                "A1",
                "A2",
                "B1",
                "B2",
                "C1",
                "C2"
            ]
        },
        "whisker_types.ContentJob": {
            "type": "object",
            "properties": {
                "cefr_level": {
                    "$ref": "#/definitions/whisker_types.CEFRLevel"
                },
                "created_at": {
                    "type": "string"
                },
                "database_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language_code": {
                    "$ref": "#/definitions/whisker_types.LanguageCode"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/whisker_types.ContentJobStatus"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "whisker_types.ContentJobStatus": {
            "type": "string",
            "enum": [
                "creation",
                "pending",
                "running",
                "complete",
                "failed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "ContentJobStatusCreation",
                "ContentJobStatusPending",
                "ContentJobStatusRunning",
                "ContentJobStatusComplete",
                "ContentJobStatusFailed",
                "ContentJobStatusCancelled"
            ]
        },
        "whisker_types.LanguageCode": {
            "type": "string",
            "enum": [
                "en",
                "es",
                "fr"
            ],
            "x-enum-varnames": [
                "EnglishCode",
                "SpanishCode",
                "FrenchCode"
            ]
        },
        "whisker_types.StoredContent": {
            "type": "object",
            "properties": {
                "markdown": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "workspaces.Content": {
            "type": "object",
            "required": [
                "cefr_level",
                "created_at",
                "database_id",
                "id",
                "language_code",
                "name"
            ],
            "properties": {
                "cefr_level": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/whisker_types.CEFRLevel"
                        }
                    ],
                    "example": "A1"
                },
                "created_at": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                },
                "database_id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "language_code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/whisker_types.LanguageCode"
                        }
                    ],
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "My Content"
                }
            }
        },
        "workspaces.CreateContentRequest": {
            "type": "object",
            "required": [
                "cefr_level",
                "language_code",
                "link",
                "name"
            ],
            "properties": {
                "cefr_level": {
                    "$ref": "#/definitions/whisker_types.CEFRLevel"
                },
                "language_code": {
                    "description": "Content creation parameters",
                    "allOf": [
                        {
                            "$ref": "#/definitions/whisker_types.LanguageCode"
                        }
                    ]
                },
                "link": {
                    "description": "Eventually need to build a more robust request body for other\nkinds of content uploads",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "workspaces.CreateContentResponse": {
            "type": "object"
        },
        "workspaces.CreateDatabaseRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "My Database"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/workspaces.DatabaseType"
                        }
                    ],
                    "example": "content"
                }
            }
        },
        "workspaces.CreateDatabaseResponse": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                }
            }
        },
        "workspaces.CreateWorkspaceRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "My Workspace"
                }
            }
        },
        "workspaces.CreateWorkspaceResponse": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                }
            }
        },
        "workspaces.Database": {
            "type": "object",
            "required": [
                "id",
                "name",
                "type",
                "workspace_id"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "name": {
                    "type": "string",
                    "example": "My Database"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/workspaces.DatabaseType"
                        }
                    ],
                    "example": "content"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                }
            }
        },
        "workspaces.DatabaseType": {
            "type": "string",
            "enum": [
                "content"
            ],
            "x-enum-varnames": [
                "DatabaseTypeContent"
            ]
        },
        "workspaces.DeleteContentResponse": {
            "type": "object"
        },
        "workspaces.DeleteDatabaseResponse": {
            "type": "object"
        },
        "workspaces.DeleteWorkspaceResponse": {
            "type": "object"
        },
        "workspaces.DeletedSummary": {
            "type": "object",
            "required": [
                "contents",
                "databases",
                "workspaces"
            ],
            "properties": {
                "contents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Content"
                    }
                },
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Database"
                    }
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Workspace"
                    }
                }
            }
        },
        "workspaces.GetContentResponse": {
            "type": "object",
            "required": [
                "content",
                "presigned_url"
            ],
            "properties": {
                "content": {
                    "$ref": "#/definitions/workspaces.Content"
                },
                "presigned_url": {
                    "type": "string"
                }
            }
        },
        "workspaces.GetIncompleteJobsResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/whisker_types.ContentJob"
                    }
                }
            }
        },
        "workspaces.GetWorkspacesResponse": {
            "type": "object",
            "required": [
                "workspaces"
            ],
            "properties": {
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Workspace"
                    }
                }
            }
        },
        "workspaces.QueryDatabaseRequest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/workspaces.DatabaseType"
                        }
                    ],
                    "example": "content"
                }
            }
        },
        "workspaces.QueryDatabaseResponse": {
            "type": "object",
            "required": [
                "id",
                "name",
                "type",
                "workspace_id"
            ],
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Content"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "name": {
                    "type": "string",
                    "example": "My Database"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/workspaces.DatabaseType"
                        }
                    ],
                    "example": "content"
                },
                "workspace_id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                }
            }
        },
        "workspaces.SoftDeleteStatus": {
            "type": "string",
            "enum": [
                "no",
                "soft_delete",
                "hard_delete"
            ],
            "x-enum-varnames": [
                "SoftDeleteStatusNo",
                "SoftDeleteStatusSoftDelete",
                "SoftDeleteStatusHardDelete"
            ]
        },
        "workspaces.Workspace": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "name": {
                    "type": "string",
                    "example": "My Workspace"
                }
            }
        },
        "workspaces.WorkspacesSummary": {
            "type": "object",
            "required": [
                "databases",
                "workspaces"
            ],
            "properties": {
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Database"
                    }
                },
                "workspaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/workspaces.Workspace"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "JWT Authorization header using Bearer",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.squeak.today",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Squeak API",
	Description:      "Backend API for Squeak Platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
