/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabasesDatabaseIdRouteImport } from './routes/databases/$databaseId'
import { Route as DatabasesDatabaseIdContentContentIdRouteImport } from './routes/databases_/$databaseId/content.$contentId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesDatabaseIdRoute = DatabasesDatabaseIdRouteImport.update({
  id: '/databases/$databaseId',
  path: '/databases/$databaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesDatabaseIdContentContentIdRoute =
  DatabasesDatabaseIdContentContentIdRouteImport.update({
    id: '/databases_/$databaseId/content/$contentId',
    path: '/databases/$databaseId/content/$contentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/databases/$databaseId/content/$contentId': typeof DatabasesDatabaseIdContentContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/databases/$databaseId/content/$contentId': typeof DatabasesDatabaseIdContentContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/update-password': typeof UpdatePasswordRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/databases_/$databaseId/content/$contentId': typeof DatabasesDatabaseIdContentContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/update-password'
    | '/databases/$databaseId'
    | '/databases/$databaseId/content/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/update-password'
    | '/databases/$databaseId'
    | '/databases/$databaseId/content/$contentId'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/signup'
    | '/update-password'
    | '/databases/$databaseId'
    | '/databases_/$databaseId/content/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  DatabasesDatabaseIdRoute: typeof DatabasesDatabaseIdRoute
  DatabasesDatabaseIdContentContentIdRoute: typeof DatabasesDatabaseIdContentContentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/databases/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases_/$databaseId/content/$contentId': {
      id: '/databases_/$databaseId/content/$contentId'
      path: '/databases/$databaseId/content/$contentId'
      fullPath: '/databases/$databaseId/content/$contentId'
      preLoaderRoute: typeof DatabasesDatabaseIdContentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  DatabasesDatabaseIdRoute: DatabasesDatabaseIdRoute,
  DatabasesDatabaseIdContentContentIdRoute:
    DatabasesDatabaseIdContentContentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
