name: Terraform Linting and Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build API Lambda ZIP
      run: |
        cd api
        go mod download
        chmod +x build-for-lambda.sh
        ./build-for-lambda.sh
      working-directory: .

    - name: Build Lambda Lambda ZIP
      run: |
        cd lambda
        go mod download
        chmod +x build-for-lambda.sh
        ./build-for-lambda.sh
      working-directory: .

    - name: Build Queue Filler Lambda ZIP
      run: |
        cd queue_filler
        go mod download
        chmod +x build-for-lambda.sh
        ./build-for-lambda.sh
      working-directory: .

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: infrastructure
      env:
        TF_WORKSPACE: ${{ 'prod' }}

    - name: Terraform Format
      run: terraform fmt -check -recursive
      working-directory: infrastructure

    - name: Terraform Validate
      run: terraform validate
      working-directory: infrastructure
